server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

# Route static configuration
#  gateway:
#    routes:
#      - id: customer-service
#        uri: lb://customer-service
#        predicates:
#          - Path=/customers/**
#      - id: product-service
#        uri: lb://product-service
#        predicates:
#          - Path=/products/**
